# This is a basic workflow to help you get started with Actions

name: gh-pages deploy

on:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup & Install
        uses: actions/setup-node@v1.1.0
        with:
          node-version: '12.x'

      - name: Checkout Master
        uses: actions/checkout@v2

      - name: install dependencies
        run: npm ci

      - name: Deploy
        run: |
          git config user.name "omar2205" && git config user.email "omar2205a@yahoo.com"
          npm run gh-pages-deploy

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#     - uses: actions/checkout@v2

#     # Runs a single command using the runners shell
#     - name: Run a one-line script
#       run: echo Hello, world!

#     # Runs a set of commands using the runners shell
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
